import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

// To be honest, this whole class has been generated by ChatGPT because it's not the point of this course to write that.
public class FileLoader {
    private String fileName;

    public FileLoader(String fileName) {
        this.fileName = fileName;
    }

    public ArrayList<String> readLines() {
        ArrayList<String> out = new ArrayList<String>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            String line = null;

            while ((line = reader.readLine()) != null) {
                out.add(line);
            }

            reader.close();
            return out;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;

    }

    public void addLine(String line) {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true));
            writer.write(line);
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public ArrayList<String>  modifyLine(String target, String replacement) {
        try {
            File file = new File(fileName);
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line = null;
            StringBuilder stringBuilder = new StringBuilder();

            while ((line = reader.readLine()) != null) {
                if (line.contains(target)) {
                    line = line.replace(target, replacement);
                }
                stringBuilder.append(line + "\n");
            }

            reader.close();

            FileWriter writer = new FileWriter(file);
            writer.write(stringBuilder.toString());
            writer.close();
            return this.readLines();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static void main(String[] args) {
        FileLoader editor = new FileLoader(".history");
        //editor.readLines();
        editor.addLine("This is a new line.");
        //editor.readLines();
        editor.modifyLine("This is a new line.", "replacement string");
        editor.readLines();
    }
}