import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.BorderFactory;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.ActionEvent;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.plaf.InsetsUIResource;

/**
 * This class launches the connection client 
 * Once the program exits, an actionlistener is triggered in ClientImpl and the execution continues.
 * 
 * *NOTE* This class was created using WindowsBuilder in Eclipse, then adapted to suit our needs.
 */
public class ConnexionClient {

	public JFrame frame;
	private JPasswordField pwdPassword;
	private JTextField txtUsername;

	/**
	 * Create the application.
	 */
	public ConnexionClient() {
		initialize();
        frame.setVisible(true);
		frame.pack();
        frame.setLocationRelativeTo(null);
	}

	/**
	 * Initialize the contents of the frame.
	 * This code is generated by Eclipse windowsbuilder. 
	 */
	private void initialize() {
		// main frame
		frame = new JFrame();
		frame.setBounds(100, 100, 511, 710);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		// main panel
		JPanel panel = new JPanel();
		frame.getContentPane().add(panel, BorderLayout.CENTER);
		panel.setLayout(new GridLayout(3, 1));
		
		// username panel
		JPanel user = new JPanel();
		user.setBorder(BorderFactory.createEmptyBorder(50, 10, 50, 10));
		panel.add(user);
		user.setLayout(new BorderLayout(0, 0));
		
		JLabel lblUsername = new JLabel("Username :");
		lblUsername.setFont(new Font("Nimbus Sans", Font.BOLD, 25));
		user.add(lblUsername, BorderLayout.NORTH);
		
		txtUsername = new JTextField();
		txtUsername.setFont(new Font("Nimbus Sans", Font.BOLD, 40));
		user.add(txtUsername, BorderLayout.CENTER);
		txtUsername.setColumns(10);
        txtUsername.setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY));
        txtUsername.setMargin(new InsetsUIResource(0, 20, 0, 20));
		txtUsername.addKeyListener(new KeyListener(){
			@Override
			public void keyPressed(KeyEvent e) {
				// do nothing
			}

			@Override
			public void keyReleased(KeyEvent e) {
				// when enter is pressed, connect
				if (e.getKeyCode() == KeyEvent.VK_ENTER){
					connect();
				}
			}

			@Override
			public void keyTyped(KeyEvent e) {
				// do nothing
			}
	});
		
		// password panel
		JPanel pass = new JPanel();
		pass.setBorder(BorderFactory.createEmptyBorder(50, 10, 50, 10));
		panel.add(pass);
		pass.setLayout(new BorderLayout(0, 0));
		
		JLabel lblPassword = new JLabel("Password :");
		lblPassword.setFont(new Font("Nimbus Sans", Font.BOLD, 25));
		pass.add(lblPassword, BorderLayout.NORTH);
		
		pwdPassword = new JPasswordField();
		pwdPassword.setText("");
		pwdPassword.setFont(new Font("Nimbus Sans", Font.BOLD, 40));
        pwdPassword.setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY));
        pwdPassword.addKeyListener(new KeyListener(){
                @Override
                public void keyPressed(KeyEvent e) {
                    // do nothing
                }

                @Override
                public void keyReleased(KeyEvent e) {
                    // when enter is pressed, connect
                    if (e.getKeyCode() == KeyEvent.VK_ENTER){
                        connect();
                    }
                }

                @Override
                public void keyTyped(KeyEvent e) {
                    // do nothing
                }
        });
		pass.add(pwdPassword, BorderLayout.CENTER);
		
		// login panel
		JPanel login = new JPanel();
		panel.add(login);
		login.setLayout(new BorderLayout(0, 0));
		login.setBorder(BorderFactory.createEmptyBorder(50, 30, 50, 30));
		
		JButton btnLogin = new JButton("LOGIN");
		btnLogin.setFont( new Font("Nimbus Sans", Font.BOLD, 60));
		btnLogin.setBackground(new Color(192, 245, 0));
		btnLogin.setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY));
		btnLogin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
                connect();
			}
		});
        
		login.add(btnLogin, BorderLayout.CENTER);
	}

	/**
	 * trigger connect. close the gui, the caller class will get the user:pass values
	 */
    private void connect(){
        String username = txtUsername.getText();
		// You can't have ':' in your name because ':' is used to separate 
		// the username from the salt and the password
        if (username.contains(":")){
            JOptionPane.showMessageDialog(new JFrame(), "Username can't contain ':'.", "Dialog", JOptionPane.ERROR_MESSAGE);
            txtUsername.setText("");
            return;
        }
		
        frame.dispose();
    }

	/**
	 * getter of username
	 * @return the username entered
	 */
    public String getUsername(){
		String user = this.txtUsername.getText();
		if (user.length()<3){
			return null;
		} else {
			return this.txtUsername.getText();
		}
    }

	/**
	 * getter of the password
	 * @return the password IN CLEAR TEXT
	 */
    public String getPassword(){
		String pwd = new String(this.pwdPassword.getPassword());
		if (pwd.length() < 8){
			System.out.println("This password is less than 8 caracters");
			return null;
		} else if (isAlpha(pwd)){
			System.out.println("This password contains only letters");
			return null;
		}
        return pwd;
    }

	/**
	 * Check if password is only letters
	 * @param s password
	 * @return true if only letters
	 */
	private Boolean isAlpha(String s ){
		return s.matches("[a-zA-Z]+");
	}



}