import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/**
 * This class loads the content of a file, makes it possible to append lines etc.
 * This class was partially generated by ChatGPT.
 */
public class FileLoader {
    private String fileName;

    /**
     * Constructor
     * @param fileName the name of the file to open
     */
    public FileLoader(String fileName) {
        this.fileName = fileName;
    }

    /**
     * get the lines contained in the file
     * @return arraylist containing all the lines
     */
    public ArrayList<String> readLines() {
        ArrayList<String> out = new ArrayList<String>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            String line = null;

            while ((line = reader.readLine()) != null) {
                out.add(line);
            }

            reader.close();
            return out;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;

    }

    /**
     * addLine to a file
     * Synchronized, to avoid adding lines on top of each others and losing data
     * @param line the line to append at the end of the file
     */
    public synchronized void addLine(String line) {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true));
            writer.write(line);
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Modify the lines containing trgt string by rplc string.
     * This is not used, but has the objective of making it possible to change a user's password.
     * @param trgt string to replace
     * @param rplc new string
     * @return the new file
     */
    public synchronized ArrayList<String>  modifyLine(String trgt, String rplc) {
        try {
            File file = new File(fileName);
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line = null;
            StringBuilder stringBuilder = new StringBuilder();

            while ((line = reader.readLine()) != null) {
                if (line.contains(trgt)) {
                    line = line.replace(trgt, rplc);
                }
                stringBuilder.append(line + "\n");
            }

            reader.close();

            FileWriter writer = new FileWriter(file);
            writer.write(stringBuilder.toString());
            writer.close();
            return this.readLines();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
}